name: GitHub Actions

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: WPCS validate
              run: composer cs

            - name: Tests coverage
              run: XDEBUG_MODE=coverage vendor/phpunit/phpunit/phpunit --configuration tests/phpunit/phpunit.xml --coverage-clover coverage.xml

            - name: Send to coveralls
              run: php vendor/bin/php-coveralls -v
              env:
                COVERALLS_RUN_LOCALLY: 1
                COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
